### ISSUE TITLE
einops version

### ISSUE THREAD

**Issue by JackCloudman** [FailSpy/abliterator#19]
https://github.com/FailSpy/abliterator/blob/7a86564d36f3831de9428000a9164e9b14992898/requirements.txt#L2
The version should be `0.8.0` i think.
Source: [https://pypi.org/project/einops/#history](https://pypi.org/project/einops/#history)

**Comment by FailSpy** [comment]
want to make a PR so I can credit you for this?

**Comment by JackCloudman** [comment]
Related PR: https://github.com/FailSpy/abliterator/pull/21

**Comment by FailSpy** [comment]
Closed thanks to #21 :)
